# Sample WF Azure Machine Learning  
name: aml-deploy-infrastructure-submit-train 
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy_train.yml'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
        
    # Connect or Create the Azure Machine Learning Workspace
    - name: deploy all resources
      id: aml_configure
      uses: mlopstemplates/aml_configure@v1.0
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          armtemplate_file: "arm_deploy.json"
          armtemplateparams_file: "arm_deploy.params.json"
          resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          mapped_params: '{"patToken":"${{secrets.PATTOKEN}}", "computeName":"mycluster", "workspaceName":"${{secrets.WORKSPACE_NAME}}" }'

    # Deploys function app and creates an event grid subscription
    - name: Create Event Subscription
      id: azure_eventgridsubscriber
      uses: mlopstemplates/azure_eventgridsubscriber@master
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          events_to_subscribe: |
            Microsoft.MachineLearningServices.RunCompleted
            Microsoft.MachineLearningServices.ModelRegistered
          provider_type: "Microsoft.MachineLearningServices/workspaces/${{secrets.WORKSPACE_NAME}}"
          resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          pattoken: ${{secrets.PATTOKEN}}

    - name: Display subscription endpoint
      run: |
        echo subscription-endpoint: ${{ steps.azure_eventgridsubscriber.outputs.destination_url}}


    # now send for training.
    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@ashishonce/demochanges
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group:  ${{ secrets.AZURE_RESOURCE_GROUP }}
          workspace_name: ${{secrets.WORKSPACE_NAME}}
      
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
